language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Vr93mJYg9baw9ArSnpMHc38GO21UVCwBFcUIW2411vthmhj4MiqBRDC/oxH6ERW/ttLH4KlyWxVSAqhlg8LFULCDbpbEfuLyCy/lrIbg1u78+dqDOuD7h/UhJ1KYV2BhLzxb+d+d5VRroOw9cezqxR+nkwAjs/GFFQvOITIyedVrHxu/tlB72z9uLoq3hBq9aso9HgwYC5v81XRXdWzvjU7jt94/wLCyB4VAs+6c5wlsp35qy7X+mkPv4wdaigg78cDown77nbX8GDzonf4MbKzDs9XzmlPB2PKJWiorie2/DMIogjxikwjGQaSClDQMi1c6u7yf4E/nf3s8D3bYQnYc0ZFxowupK+oHZDLBfyMGHPGzMKiG9KBZhEsBV5przPan1KNQs4vG7mdpa0THeMI3ygJerVxEQE5Catx6508Ont5oIaqWHrirAGm8G4qZhphRB7Z2Gqpt0KKuLZr6JeilEIL5rNuwtwEdBUhfJF4J834bpfqNf/2H31Xr05kB4WtMJ/sNo16aahoM6EJrH8r1JelxfE1eg2OrbYxYEiyO1DWj0ZKyYhGxXKFBNfY1bDnHFiVbMUPtd0ooHWUurIKRiSbxgyb3oP2aa120neqfocZoD0UPtLb8+6tqDR5h2+M1raqXMK8JkkMXRfgPI+VX0AzkNyNb0ix5KYAY2sQ=
  app: floating-lowlands-70666
  on:
    repo: kbuonforte/pc-ui
